### ISSUE TITLE
Unable to load plugin?

### ISSUE THREAD

**Issue by raka-everton** [yzh503/obsidian-aicommander-plugin#1]
Hello there

I am trying to install AI Commander, and just to be clear only the main.ts and manifest.json go in the plugin folder, correct? No other files?

Because I did so and I am getting a "failed to load plugin ai-commander" error.

**Comment by yzh503** [comment]
@raka-everton That is correct. No other file is needed. Are you using Windows or MacOS? Which version of this plugin did you load?

**Comment by mikaeljagelid** [comment]
Same issue here: 
1. Just downloaded the latest release, 1.2.3. 
2. Created the folder `obsidian-aicommander-plugin` in my  `<vault>/.obsidian/plugins/`.
3. Copied `manifest.json` and `main.ts` (note that the installation instructions says `main.js`)
4. Opened Obsidian Settings and `Community Plugins`, clicked the `Reload Plugins`.
5. AI Commander shows up in my list of installed plugins as disabled.
6. When I try to enable the plugin with the toggle button, Obsidian shows the error alert "Failed to load the plugin ai-commander".
7. Restarted Obsidian and it still  fails to load.

I'm running MacOS Ventura 13.0 with Obsidian 1.1.16 with installer version 0.15.9.

**Comment by raka-everton** [comment]
> @raka-everton That is correct. No other file is needed. Are you using Windows or MacOS? Which version of this plugin did you load?

Obsidian 1.1.16, same details as @mikaeljagelid except on Windows.

**Comment by yzh503** [comment]
@mikaeljagelid @raka-everton can you try copying `main.js` into `obsidian-aicommander-plugin`? You can find it in the release page.

**Comment by mikaeljagelid** [comment]
Tried it, working fine now. Thank you!

**Comment by raka-everton** [comment]
Working.. Thank you!
